server:
  port: 8084

spring:
  application:
    name: movement-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/movement

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

controller:
  bank-account-movement:
    base-path: /bank-account
    method:
      register-deposit: /deposit
      register-withdrawal: /withdrawal
      get-by-saving-account-id: /saving/{id}
      get-by-fixed-term-account-id: /fixed-term/{id}
      get-by-checking-account-id: /checking/{id}
  credit-movement:
    base-path: /credit
    method:
      register-payment: /payment
      register-consumption: /consumption
      get-by-credit-card-id: /credit-card/{id}
  method:
    getAll:
    getById: /{id}
    register:
    updateById: /{id}
    deleteById: /{id}
  path-variable:
    id: id

bank-account-service:
  base-url: http://localhost:8099/bank-accounts
  method:
    get-saving-account-by-id: /saving/{id}
    get-fixed-term-account-by-id: /fixed-term/{id}
    get-checking-account-by-id: /checking/{id}
    update-saving-account-by-id: /saving/{id}
    update-fixed-term-account-by-id: /fixed-term/{id}
    update-checking-account-by-id: /checking/{id}

credit-service:
  base-url: http://localhost:8099/credits
  method:
    get-credit-card-by-id: /credit-card/{id}
    update-credit-card-by-id: /credit-card/{id}
